// SPDX-License-Identifier: MIT
import type { WeeklyRepositoryReport } from "./weekly-report";
import type { ReportDeliveryProvider } from "./report-delivery";

export interface GitHubReportDestination {
  owner: string;
  repo: string;
  token: string;
  kind: "issue" | "discussion";
  categoryId?: string;
  siteUrl: string;
}

const githubHeaders = (token: string) => ({
  Authorization: `Bearer ${token}`,
  Accept: "application/vnd.github+json",
  "Content-Type": "application/json",
  "User-Agent": "github-traffic-analytics-reports",
  "X-GitHub-Api-Version": "2022-11-28",
});

const metric = (count: number | null) =>
  count === null ? "Unavailable" : count.toLocaleString("en-US");

export function formatGitHubReport(report: WeeklyRepositoryReport, siteUrl: string): string {
  const [owner, repo] = report.fullName.split("/");
  const reportUrl = `${siteUrl.replace(/\/$/, "")}/repo/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}`;
  const period = report.cadence === "weekly" ? "Weekly" : "Monthly";
  return [
    `## GitHub Traffic Analytics — ${period} Report`,
    "",
    `${report.period.from} to ${report.period.to} · complete UTC days`,
    "",
    "| Metric | This period | Previous period |",
    "| --- | ---: | ---: |",
    `| Stars gained | ${metric(report.stars.count)} | ${metric(report.stars.previous)} |`,
    `| Views | ${metric(report.views.count)} | ${metric(report.views.previous)} |`,
    `| Clones | ${metric(report.clones.count)} | ${metric(report.clones.previous)} |`,
    "",
    "### What changed",
    "",
    ...report.highlights.map((highlight) => `- ${highlight}`),
    ...(report.strongestAnomaly
      ? ["", `**Strongest observed signal:** ${report.strongestAnomaly.explanation}`]
      : []),
    "",
    `View the owner report and manage delivery: ${reportUrl}`,
    "",
    "Generated by [GitHub Traffic Analytics](https://github.com/aliammari1/github-traffic-analytics). Release timing does not establish cause. Incomplete observations appear as unavailable.",
  ].join("\n");
}

interface GraphqlResponse<T> {
  data?: T;
  errors?: Array<{ message: string }>;
}

async function graphql<T>(
  fetcher: typeof fetch,
  token: string,
  query: string,
  variables: Record<string, unknown>
): Promise<T> {
  const response = await fetcher("https://api.github.com/graphql", {
    method: "POST",
    headers: githubHeaders(token),
    body: JSON.stringify({ query, variables }),
    signal: AbortSignal.timeout(15_000),
  });
  if (!response.ok) throw new Error(`GitHub GraphQL returned ${response.status}`);
  const payload = (await response.json()) as GraphqlResponse<T>;
  if (payload.errors?.length || !payload.data)
    throw new Error("GitHub GraphQL rejected report delivery");
  return payload.data;
}

export async function discussionCategories(
  owner: string,
  repo: string,
  token: string,
  fetcher: typeof fetch = fetch
): Promise<Array<{ id: string; name: string }>> {
  const data = await graphql<{
    repository: { discussionCategories: { nodes: Array<{ id: string; name: string }> } } | null;
  }>(
    fetcher,
    token,
    `
      query ($owner: String!, $repo: String!) {
        repository(owner: $owner, name: $repo) {
          discussionCategories(first: 25) {
            nodes {
              id
              name
            }
          }
        }
      }
    `,
    { owner, repo }
  );
  return data.repository?.discussionCategories.nodes ?? [];
}

export class GitHubReportProvider implements ReportDeliveryProvider<GitHubReportDestination> {
  constructor(private readonly fetcher: typeof fetch = fetch) {}

  async deliver(
    report: WeeklyRepositoryReport,
    destination: GitHubReportDestination,
    deliveryKey: string
  ): Promise<string> {
    const keyBytes = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(deliveryKey));
    const marker = `<!-- github-traffic-analytics:${[...new Uint8Array(keyBytes)]
      .map((byte) => byte.toString(16).padStart(2, "0"))
      .join("")} -->`;
    const body = `${formatGitHubReport(report, destination.siteUrl)}\n\n${marker}`;
    const title = `GitHub Traffic Analytics: ${report.cadence} report ending ${report.period.to}`;
    if (destination.kind === "issue") {
      const existing = await this.fetcher(
        `https://api.github.com/repos/${encodeURIComponent(destination.owner)}/${encodeURIComponent(destination.repo)}/issues?state=all&sort=created&direction=desc&per_page=100`,
        { headers: githubHeaders(destination.token), signal: AbortSignal.timeout(15_000) }
      );
      if (!existing.ok) throw new Error(`GitHub Issue lookup returned ${existing.status}`);
      const issues = (await existing.json()) as Array<{
        title: string;
        html_url: string;
        body: string | null;
        pull_request?: unknown;
      }>;
      const duplicate = issues.find(
        (issue) => !issue.pull_request && issue.title === title && issue.body?.includes(marker)
      );
      if (duplicate) return duplicate.html_url;
      const response = await this.fetcher(
        `https://api.github.com/repos/${encodeURIComponent(destination.owner)}/${encodeURIComponent(destination.repo)}/issues`,
        {
          method: "POST",
          headers: githubHeaders(destination.token),
          body: JSON.stringify({ title, body }),
          signal: AbortSignal.timeout(15_000),
        }
      );
      if (!response.ok) throw new Error(`GitHub Issue creation returned ${response.status}`);
      const result = (await response.json()) as { id?: number; html_url?: string };
      if (!result.html_url) throw new Error("GitHub Issue response omitted its URL");
      return result.html_url;
    }
    if (!destination.categoryId) throw new Error("A Discussion category is required");
    const categories = await discussionCategories(
      destination.owner,
      destination.repo,
      destination.token,
      this.fetcher
    );
    if (!categories.some((category) => category.id === destination.categoryId))
      throw new Error("Discussion category is no longer available");
    const data = await graphql<{
      repository: {
        id: string;
        discussions: { nodes: Array<{ title: string; url: string; body: string }> };
      } | null;
    }>(
      this.fetcher,
      destination.token,
      `
        query ($owner: String!, $repo: String!) {
          repository(owner: $owner, name: $repo) {
            id
            discussions(first: 100, orderBy: { field: CREATED_AT, direction: DESC }) {
              nodes {
                title
                url
                body
              }
            }
          }
        }
      `,
      { owner: destination.owner, repo: destination.repo }
    );
    if (!data.repository) throw new Error("Repository is no longer available");
    const duplicate = data.repository.discussions.nodes.find(
      (item) => item.title === title && item.body.includes(marker)
    );
    if (duplicate) return duplicate.url;
    const created = await graphql<{
      createDiscussion: { discussion: { url: string } | null } | null;
    }>(
      this.fetcher,
      destination.token,
      `
        mutation ($repositoryId: ID!, $categoryId: ID!, $title: String!, $body: String!) {
          createDiscussion(
            input: {
              repositoryId: $repositoryId
              categoryId: $categoryId
              title: $title
              body: $body
            }
          ) {
            discussion {
              url
            }
          }
        }
      `,
      { repositoryId: data.repository.id, categoryId: destination.categoryId, title, body }
    );
    const url = created.createDiscussion?.discussion?.url;
    if (!url) throw new Error("GitHub Discussion response omitted its URL");
    return url;
  }
}
