// SPDX-License-Identifier: MIT
import { appendFile } from "node:fs/promises";

const API = "https://api.github.com";
const VERSION = "2026-03-10";
const DAY_MS = 86_400_000;

function input(name, fallback = "") {
  return process.env[`INPUT_${name.toUpperCase()}`]?.trim() || fallback;
}

function apiPath(value) {
  if (typeof value !== "string" || value.includes("..")) {
    throw new Error("Invalid API path segment");
  }
  return value
    .split("/")
    .filter(Boolean)
    .map((segment) => encodeURIComponent(segment))
    .join("/");
}

function safeGitHubUrl(path) {
  if (typeof path !== "string" || !path.startsWith("/") || path.includes("..")) {
    throw new Error("Invalid GitHub API path");
  }
  const url = new URL(path, API);
  if (url.origin !== "https://api.github.com") {
    throw new Error("Invalid GitHub API origin");
  }
  return url;
}

async function github(path, token, options = {}) {
  const targetUrl = safeGitHubUrl(path);
  const response = await fetch(targetUrl, {
    method: options.method || "GET",
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
      "User-Agent": "github-traffic-analytics-action",
      "X-GitHub-Api-Version": VERSION,
    },
    ...(options.body ? { body: JSON.stringify(options.body) } : {}),
    signal: AbortSignal.timeout(20_000),
  });
  if (response.status === 404 && options.allowMissing) return null;
  if (!response.ok) {
    if (response.status === 403 && path.includes("/traffic/"))
      throw new Error(
        "GitHub denied traffic access. traffic_token needs Administration: read on this repository; the workflow GITHUB_TOKEN cannot request that permission."
      );
    throw new Error(`GitHub API returned ${response.status} for ${path.split("?")[0]}`);
  }
  return response.status === 204 ? null : response.json();
}

function day(value) {
  return typeof value === "string" && /^\d{4}-\d{2}-\d{2}$/.test(value) ? value : null;
}

function mergeDaily(existing, views, clones, today) {
  const byDay = new Map(
    Array.isArray(existing?.daily)
      ? existing.daily.filter((entry) => day(entry.day)).map((entry) => [entry.day, entry])
      : []
  );
  for (const [metric, data] of [
    ["views", views],
    ["clones", clones],
  ]) {
    const series = data?.[metric];
    if (!Array.isArray(series)) throw new Error(`GitHub omitted the ${metric} daily series`);
    for (const point of series) {
      const date = day(point.timestamp?.slice(0, 10));
      if (
        !date ||
        date >= today ||
        !Number.isInteger(point.count) ||
        !Number.isInteger(point.uniques)
      )
        continue;
      const previous = byDay.get(date) ?? { day: date };
      byDay.set(date, {
        ...previous,
        [metric]: { count: point.count, uniques: point.uniques },
      });
    }
  }
  return [...byDay.values()].sort((a, b) => a.day.localeCompare(b.day));
}

function csv(daily) {
  const lines = ["day,views,view_uniques,clones,clone_uniques"];
  for (const row of daily)
    lines.push(
      [
        row.day,
        row.views?.count ?? "",
        row.views?.uniques ?? "",
        row.clones?.count ?? "",
        row.clones?.uniques ?? "",
      ].join(",")
    );
  return `${lines.join("\n")}\n`;
}

function completeSum(daily, metric, endingOn) {
  const rows = new Map(daily.map((row) => [row.day, row]));
  const end = Date.parse(`${endingOn}T00:00:00Z`);
  let sum = 0;
  for (let offset = 0; offset < 7; offset++) {
    const date = new Date(end - offset * DAY_MS).toISOString().slice(0, 10);
    const count = rows.get(date)?.[metric]?.count;
    if (!Number.isInteger(count)) return null;
    sum += count;
  }
  return sum;
}

function summary(fullName, daily, endingOn, branch, prefix) {
  const views = completeSum(daily, "views", endingOn);
  const clones = completeSum(daily, "clones", endingOn);
  return [
    `# ${fullName} traffic archive`,
    "",
    `Latest complete UTC day: ${endingOn}`,
    "",
    "| Last seven complete days | Count |",
    "| --- | ---: |",
    `| Views | ${views === null ? "Unavailable (incomplete capture)" : views.toLocaleString("en-US")} |`,
    `| Clones | ${clones === null ? "Unavailable (incomplete capture)" : clones.toLocaleString("en-US")} |`,
    "",
    `Daily history: [JSON](${prefix}/daily.json) · [CSV](${prefix}/daily.csv)`,
    "",
    `Captured top referrers and paths are in \`${prefix}/sources/\`. Each source list covers GitHub's rolling 14-day window; it is not a per-day referral breakdown.`,
    "",
    `Archive branch: \`${branch}\`. Generated by [GitHub Traffic Analytics Lite](https://github.com/aliammari1/github-traffic-analytics).`,
    "",
  ].join("\n");
}

async function blob(repoPath, token, content) {
  const result = await github(`${repoPath}/git/blobs`, token, {
    method: "POST",
    body: { content, encoding: "utf-8" },
  });
  return result.sha;
}

async function archive(repoPath, token, branch, files) {
  const refPath = `${repoPath}/git/ref/heads/${apiPath(branch)}`;
  const currentRef = await github(refPath, token, { allowMissing: true });
  const parent = currentRef?.object?.sha ?? null;
  const commit = parent ? await github(`${repoPath}/git/commits/${parent}`, token) : null;
  const tree = [];
  for (const [path, content] of files)
    tree.push({ path, mode: "100644", type: "blob", sha: await blob(repoPath, token, content) });
  const createdTree = await github(`${repoPath}/git/trees`, token, {
    method: "POST",
    body: { ...(commit ? { base_tree: commit.tree.sha } : {}), tree },
  });
  const createdCommit = await github(`${repoPath}/git/commits`, token, {
    method: "POST",
    body: {
      message: "chore(traffic): archive completed GitHub traffic days",
      tree: createdTree.sha,
      parents: parent ? [parent] : [],
    },
  });
  if (parent) {
    await github(`${repoPath}/git/refs/heads/${apiPath(branch)}`, token, {
      method: "PATCH",
      body: { sha: createdCommit.sha, force: false },
    });
  } else {
    await github(`${repoPath}/git/refs`, token, {
      method: "POST",
      body: { ref: `refs/heads/${branch}`, sha: createdCommit.sha },
    });
  }
}

async function main() {
  const fullName = process.env.GITHUB_REPOSITORY;
  const trafficToken = input("traffic_token");
  const githubToken = input("github_token");
  const branch = input("branch", "traffic-history");
  const prefix = input("path_prefix", "data").replace(/^\/+|\/+$/g, "");
  const allowPublicArchive = input("allow_public_archive", "false") === "true";
  if (!fullName || !/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(fullName) || fullName.includes(".."))
    throw new Error("GITHUB_REPOSITORY is missing or invalid");
  if (!trafficToken || !githubToken)
    throw new Error("Both traffic_token and github_token are required");
  if (
    !/^[A-Za-z0-9._/-]+$/.test(branch) ||
    branch.includes("..") ||
    branch.startsWith("/") ||
    branch.endsWith("/")
  )
    throw new Error("Choose a valid archive branch");
  if (!prefix || !/^[A-Za-z0-9._/-]+$/.test(prefix) || prefix.includes(".."))
    throw new Error("Choose a valid archive path prefix");
  const repoPath = `/repos/${apiPath(fullName)}`;
  const repository = await github(repoPath, githubToken);
  if (repository.default_branch === branch)
    throw new Error("The archive branch must differ from the repository's default branch");
  if (!repository.private && !allowPublicArchive)
    throw new Error(
      "This repository is public. Set allow_public_archive: true only if publishing its traffic counts is intentional."
    );
  const today = new Date().toISOString().slice(0, 10);
  const endingOn = new Date(Date.parse(`${today}T00:00:00Z`) - DAY_MS).toISOString().slice(0, 10);
  const [views, clones, referrers, paths] = await Promise.all([
    github(`${repoPath}/traffic/views?per=day`, trafficToken),
    github(`${repoPath}/traffic/clones?per=day`, trafficToken),
    github(`${repoPath}/traffic/popular/referrers`, trafficToken),
    github(`${repoPath}/traffic/popular/paths`, trafficToken),
  ]);
  const archivePath = `${repoPath}/contents/${apiPath(`${prefix}/daily.json`)}?ref=${encodeURIComponent(branch)}`;
  const branchRef = await github(`${repoPath}/git/ref/heads/${apiPath(branch)}`, githubToken, {
    allowMissing: true,
  });
  const previous = await github(archivePath, githubToken, { allowMissing: true });
  const markerPath = `${repoPath}/contents/.github-traffic-analytics.json?ref=${encodeURIComponent(branch)}`;
  const marker = await github(markerPath, githubToken, { allowMissing: true });
  if (branchRef && !marker)
    throw new Error("Archive branch exists without the GitHub Traffic Analytics marker");
  if (marker?.content) {
    const value = JSON.parse(
      Buffer.from(marker.content.replace(/\s/g, ""), "base64").toString("utf8")
    );
    if (value.repository !== fullName || value.version !== 1)
      throw new Error("Archive branch belongs to another repository or format version");
  }
  let existing = null;
  if (previous?.content) {
    const bytes = Buffer.from(previous.content.replace(/\s/g, ""), "base64");
    existing = JSON.parse(bytes.toString("utf8"));
    if (existing.repository !== fullName || existing.version !== 1)
      throw new Error("Existing archive does not match this repository or format version");
  }
  const daily = mergeDaily(existing, views, clones, today);
  const capture = {
    capturedAt: new Date().toISOString(),
    window: "GitHub rolling 14-day top lists",
    referrers,
    paths,
  };
  const files = new Map([
    [
      `${prefix}/daily.json`,
      `${JSON.stringify({ version: 1, repository: fullName, capturedAt: capture.capturedAt, daily }, null, 2)}\n`,
    ],
    [`${prefix}/daily.csv`, csv(daily)],
    [`${prefix}/sources/${today}.json`, `${JSON.stringify(capture, null, 2)}\n`],
    ["README.md", summary(fullName, daily, endingOn, branch, prefix)],
    [
      ".github-traffic-analytics.json",
      `${JSON.stringify({ version: 1, repository: fullName }, null, 2)}\n`,
    ],
  ]);
  await archive(repoPath, githubToken, branch, files);
  const output = process.env.GITHUB_OUTPUT;
  if (output)
    await appendFile(
      output,
      `branch=${branch}\nlatest_day=${endingOn}\nobserved_days=${daily.length}\n`
    );
  const stepSummary = process.env.GITHUB_STEP_SUMMARY;
  if (stepSummary)
    await appendFile(stepSummary, summary(fullName, daily, endingOn, branch, prefix));
  console.log(`Archived ${daily.length} completed UTC days to ${branch}`);
}

main().catch((cause) => {
  const message = cause instanceof Error ? cause.message : "Unknown archive failure";
  console.error(`::error::${message.replace(/[\r\n]/g, " ")}`);
  process.exitCode = 1;
});
